### ISSUE TITLE
How can i add a Path?

### ISSUE THREAD

**Issue by initiuminc1** [jiahuanyu/SVGMapView#6]
thank you very much for such a wonderful library. How can i add a path as Overlay ?

**Comment by initiuminc1** [comment]
got this. can do this by extending the SVGMapBaseOverlay

**Comment by Sukhj1nder** [comment]
initiuminc1 so how did you do this can you put up an example ?

**Comment by ryanesrapado** [comment]
@Sukhj1nder Did you get to do it? I'm in the same state...
